// GitHub theme for Monaco Editor
// Based on VS Code's GitHub theme

export const githubLightTheme = {
  base: 'vs',
  inherit: true,
  rules: [
    { token: 'comment', foreground: '6a737d' },
    { token: 'keyword', foreground: 'd73a49' },
    { token: 'string', foreground: '032f62' },
    { token: 'number', foreground: '005cc5' },
    { token: 'regexp', foreground: '032f62' },
    { token: 'type', foreground: '6f42c1' },
    { token: 'class', foreground: '6f42c1' },
    { token: 'function', foreground: '6f42c1' },
    { token: 'constant', foreground: '005cc5' },
    { token: 'variable', foreground: '24292e' },
    { token: 'variable.predefined', foreground: '005cc5' },
    { token: 'interface', foreground: '6f42c1' },
    { token: 'annotation', foreground: 'e36209' },
    { token: 'namespace', foreground: '6f42c1' },
    { token: 'package', foreground: '6f42c1' },
    { token: 'string.key', foreground: '032f62' },
    { token: 'attribute.name', foreground: '22863a' },
    { token: 'attribute.value', foreground: '032f62' },
    { token: 'tag', foreground: '22863a' },
    { token: 'tag.attribute.name', foreground: '6f42c1' },
    { token: 'tag.attribute.value', foreground: '032f62' },
    { token: 'macro', foreground: 'd73a49' },
    { token: 'entity', foreground: '6f42c1' },
    { token: 'operator', foreground: 'd73a49' },
    { token: 'property', foreground: '005cc5' },
    { token: 'variable.parameter', foreground: '24292e' },
    { token: 'variable.name', foreground: '24292e' },
  ],
  colors: {
    'editor.foreground': '#24292e',
    'editor.background': '#ffffff',
    'editor.selectionBackground': '#0366d625',
    'editor.lineHighlightBackground': '#f6f8fa',
    'editorCursor.foreground': '#24292e',
    'editorWhitespace.foreground': '#d1d5da',
    'editorIndentGuide.background': '#d1d5da',
    'editorIndentGuide.activeBackground': '#c8c8c8',
    'editor.selectionHighlightBorder': '#0366d625',
  }
};

export const githubDarkTheme = {
  base: 'vs-dark',
  inherit: true,
  rules: [
    { token: 'comment', foreground: '6a737d' },
    { token: 'keyword', foreground: 'ff7b72' },
    { token: 'string', foreground: 'a5d6ff' },
    { token: 'number', foreground: '79c0ff' },
    { token: 'regexp', foreground: 'a5d6ff' },
    { token: 'type', foreground: 'd2a8ff' },
    { token: 'class', foreground: 'd2a8ff' },
    { token: 'function', foreground: 'd2a8ff' },
    { token: 'constant', foreground: '79c0ff' },
    { token: 'variable', foreground: 'c9d1d9' },
    { token: 'variable.predefined', foreground: '79c0ff' },
    { token: 'interface', foreground: 'd2a8ff' },
    { token: 'annotation', foreground: 'f0883e' },
    { token: 'namespace', foreground: 'd2a8ff' },
    { token: 'package', foreground: 'd2a8ff' },
    { token: 'string.key', foreground: 'a5d6ff' },
    { token: 'attribute.name', foreground: '7ee787' },
    { token: 'attribute.value', foreground: 'a5d6ff' },
    { token: 'tag', foreground: '7ee787' },
    { token: 'tag.attribute.name', foreground: 'd2a8ff' },
    { token: 'tag.attribute.value', foreground: 'a5d6ff' },
    { token: 'macro', foreground: 'ff7b72' },
    { token: 'entity', foreground: 'd2a8ff' },
    { token: 'operator', foreground: 'ff7b72' },
    { token: 'property', foreground: '79c0ff' },
    { token: 'variable.parameter', foreground: 'c9d1d9' },
    { token: 'variable.name', foreground: 'c9d1d9' },
  ],
  colors: {
    'editor.foreground': '#c9d1d9',
    'editor.background': '#0d1117',
    'editor.selectionBackground': '#3392FF44',
    'editor.lineHighlightBackground': '#161b22',
    'editorCursor.foreground': '#c9d1d9',
    'editorWhitespace.foreground': '#484f58',
    'editorIndentGuide.background': '#484f58',
    'editorIndentGuide.activeBackground': '#6e7681',
    'editor.selectionHighlightBorder': '#3392FF44',
  }
};

// Monokai theme for Monaco Editor
export const monokaiTheme = {
  base: 'vs-dark',
  inherit: true,
  rules: [
    { token: 'comment', foreground: '88846f' },
    { token: 'keyword', foreground: 'f92672' },
    { token: 'string', foreground: 'e6db74' },
    { token: 'number', foreground: 'ae81ff' },
    { token: 'regexp', foreground: 'e6db74' },
    { token: 'type', foreground: '66d9ef' },
    { token: 'class', foreground: 'a6e22e' },
    { token: 'function', foreground: 'a6e22e' },
    { token: 'constant', foreground: 'ae81ff' },
    { token: 'variable', foreground: 'f8f8f2' },
    { token: 'variable.predefined', foreground: '66d9ef' },
    { token: 'interface', foreground: '66d9ef' },
    { token: 'annotation', foreground: 'f92672' },
    { token: 'namespace', foreground: 'a6e22e' },
    { token: 'package', foreground: 'a6e22e' },
    { token: 'string.key', foreground: 'e6db74' },
    { token: 'attribute.name', foreground: 'a6e22e' },
    { token: 'attribute.value', foreground: 'e6db74' },
    { token: 'tag', foreground: 'f92672' },
    { token: 'tag.attribute.name', foreground: 'a6e22e' },
    { token: 'tag.attribute.value', foreground: 'e6db74' },
    { token: 'macro', foreground: 'f92672' },
    { token: 'entity', foreground: 'a6e22e' },
    { token: 'operator', foreground: 'f92672' },
    { token: 'property', foreground: '66d9ef' },
    { token: 'variable.parameter', foreground: 'fd971f' },
    { token: 'variable.name', foreground: 'f8f8f2' },
  ],
  colors: {
    'editor.foreground': '#f8f8f2',
    'editor.background': '#272822',
    'editor.selectionBackground': '#49483e',
    'editor.lineHighlightBackground': '#3e3d32',
    'editorCursor.foreground': '#f8f8f0',
    'editorWhitespace.foreground': '#3b3a32',
    'editorIndentGuide.background': '#3b3a32',
    'editorIndentGuide.activeBackground': '#9d550fb0',
    'editor.selectionHighlightBorder': '#222218',
  }
}; 